# Generated by Django 5.2.4 on 2025-08-27 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_punchinattendance_punchoutattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staffid', models.CharField(max_length=5)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Punch_In_Time', models.TimeField(blank=True, null=True)),
                ('Punch_Out_Time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PunchInAttendance',
        ),
        migrations.DeleteModel(
            name='PunchOutAttendance',
        ),
    ]
